### ISSUE TITLE
Completed module 2 assignments

### ISSUE THREAD

**Issue by bendieklaranjo** [rbtl-fs24/md-02-assignments-bendieklaranjo#1]
@larnsce 

Hi Lars, 

I could push without any errors, but everytime I wanted to commit, I got this message:
_>>> /usr/bin/git commit -F /tmp/RtmpfTOIbd/git-commit-message-1161086b4dc.txt

*** Please tell me who you are.

Run

  git config --global user.email "you@example.com"
  git config --global user.name "Your Name"

to set your account's default identity.
Omit --global to set the identity only in this repository.

fatal: unable to auto-detect email address (got 'r2515661@application-11374403-deployment-21552438-748jm.(none)')_

Can you help me with that? I am afraid that my excercises did not commit.
Best,
Ana

**Comment by larnsce** [comment]
Hi @bendieklaranjo. Thanks for your question and for working through the assignment.

You are not the only one where this happened. I had expected that this was sorted when you worked through the git configuration assignment of module 1, but for some of you it didn't work properly.

Did your work through the first assignment for module 2?

https://rbtl-fs24.github.io/website/assignments/md-02/am-02-1-github.html

The git configuration may not have translated over to the md-02-assignments repo. Copy the code from where you did the configuration with your details over to assignment 2 and run it again. Either the whole code chunk or the content inside the code chunk to the console.

Then, commit again. Then, push your commits.

Let me know if it worked.

**Comment by bendieklaranjo** [comment]
Hi @larnsce,

Thank you for your help!
I had completed the first assignment before, and even after re-doing it, nothing changed. Eventually after copying the code chunk from the configuration file I was able to commit and push the changes 😄 

I hope it works next time without having to paste it every time! Thank you!!
